development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:c9da40919cc008839403308a432bf077@crestfish.redistogo.com:9263/
  channel_prefix: message_me_production
